INSERT INTO SUCURSAL(COD_SUCURSAL, NOMBRE)
VALUES ('C1', 'SUCURSAL LIMA');

INSERT INTO SUCURSAL(COD_SUCURSAL, NOMBRE)
VALUES ('C2', 'SUCURSAL CUSCO');

INSERT INTO SUCURSAL(COD_SUCURSAL, NOMBRE)
VALUES ('C3', 'SUCURSAL AREQUIPA');

INSERT INTO PRODUCTO(COD_PRODUCTO, NOMBRE, PRECIO)
VALUES ('P1', 'ROUTER', 99.74);

INSERT INTO PRODUCTO(COD_PRODUCTO, NOMBRE, PRECIO)
VALUES ('P2', 'TECLADO', 959.74);

INSERT INTO PRODUCTO(COD_PRODUCTO, NOMBRE, PRECIO)
VALUES ('P3', 'MOUSE', 9.74);


INSERT INTO USUARIO(COD_USUARIO, NOMBRE, USUARIO, PASSWORD, SUCURSAL_ID)
VALUES ('U1', 'HARRY COA', 'HCOA', '123456', 1);

INSERT INTO USUARIO(COD_USUARIO, NOMBRE, USUARIO, PASSWORD, SUCURSAL_ID)
VALUES ('U2', 'ERNESTO GUEVARA', 'EGUEVARA', '123456', 1);

INSERT INTO USUARIO(COD_USUARIO, NOMBRE, USUARIO, PASSWORD, SUCURSAL_ID)
VALUES ('U3', 'JULIO CARPIO', 'JCARPIO', '123456', 1);

INSERT INTO USUARIO(COD_USUARIO, NOMBRE, USUARIO, PASSWORD, SUCURSAL_ID)
VALUES ('U4', 'ANDRES SALCEDO', 'ASALCEDO', '123456', 2);

INSERT INTO USUARIO(COD_USUARIO, NOMBRE, USUARIO, PASSWORD, SUCURSAL_ID)
VALUES ('U5', 'MARIA JIMENEZ', 'MJIMENEZ', '123456', 3);

