INSERT INTO SUCURSAL(COD_SUCURSAL, NOMBRE)
VALUES ('C001', 'SUCURSAL LIMA');

INSERT INTO SUCURSAL(COD_SUCURSAL, NOMBRE)
VALUES ('C002', 'SUCURSAL CUSCO');

INSERT INTO SUCURSAL(COD_SUCURSAL, NOMBRE)
VALUES ('C003', 'SUCURSAL AREQUIPA');

INSERT INTO PRODUCTO(COD_PRODUCTO, NOMBRE, PRECIO)
VALUES ('P001', 'ROUTER', 99.74);

INSERT INTO PRODUCTO(COD_PRODUCTO, NOMBRE, PRECIO)
VALUES ('P002', 'TECLADO', 959.74);

INSERT INTO PRODUCTO(COD_PRODUCTO, NOMBRE, PRECIO)
VALUES ('P003', 'MOUSE', 9.74);


INSERT INTO USUARIO(COD_USUARIO, NOMBRE, USUARIO, PASSWORD, SUCURSAL_ID)
VALUES ('U001', 'HARRY COA', 'HCOA', '123456', 1);

INSERT INTO USUARIO(COD_USUARIO, NOMBRE, USUARIO, PASSWORD, SUCURSAL_ID)
VALUES ('U002', 'ERNESTO GUEVARA', 'EGUEVARA', '123456', 1);

INSERT INTO USUARIO(COD_USUARIO, NOMBRE, USUARIO, PASSWORD, SUCURSAL_ID)
VALUES ('U003', 'JULIO CARPIO', 'JCARPIO', '123456', 1);

INSERT INTO USUARIO(COD_USUARIO, NOMBRE, USUARIO, PASSWORD, SUCURSAL_ID)
VALUES ('U004', 'ANDRES SALCEDO', 'ASALCEDO', '123456', 2);

INSERT INTO USUARIO(COD_USUARIO, NOMBRE, USUARIO, PASSWORD, SUCURSAL_ID)
VALUES ('U005', 'MARIA JIMENEZ', 'MJIMENEZ', '123456', 3);

